In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("C:Downloads/day.csv")

In [4]:
data.head()

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0   
1        2  2011-01-02       1   0     1        0        0           0   
2        3  2011-01-03       1   0     1        0        1           1   
3        4  2011-01-04       1   0     1        0        2           1   
4        5  2011-01-05       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654   
1           2  0.363478  0.353739  0.696087   0.248539     131         670   
2           1  0.196364  0.189405  0.437273   0.248309     120        1229   
3           1  0.200000  0.212122  0.590435   0.160296     108        1454   
4           1  0.226957  0.229270  0.436957   0.186900      82        1518   

    cnt  
0   985  
1   801  
2  1349  
3  1562  
4  1600

In [6]:
data = data.drop(["instant"],1)

In [7]:
data.head()

dteday  season  yr  mnth  holiday  weekday  workingday  weathersit  \
0  2011-01-01       1   0     1        0        6           0           2   
1  2011-01-02       1   0     1        0        0           0           2   
2  2011-01-03       1   0     1        0        1           1           1   
3  2011-01-04       1   0     1        0        2           1           1   
4  2011-01-05       1   0     1        0        3           1           1   

       temp     atemp       hum  windspeed  casual  registered   cnt  
0  0.344167  0.363625  0.805833   0.160446     331         654   985  
1  0.363478  0.353739  0.696087   0.248539     131         670   801  
2  0.196364  0.189405  0.437273   0.248309     120        1229  1349  
3  0.200000  0.212122  0.590435   0.160296     108        1454  1562  
4  0.226957  0.229270  0.436957   0.186900      82        1518  1600

In [34]:
data.shape

(731, 15)

In [8]:
data.isnull().sum()

dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [9]:
data.dtypes

dteday         object
season          int64
yr              int64
mnth            int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [24]:
data.season.unique()

array([1, 2, 3, 4], dtype=int64)

In [25]:
data.yr.unique()

array([0, 1], dtype=int64)

In [26]:
data.mnth.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [27]:
data.holiday.unique()

array([0, 1], dtype=int64)

In [28]:
data.weekday.unique()

array([6, 0, 1, 2, 3, 4, 5], dtype=int64)

In [29]:
data.workingday.unique()

array([0, 1], dtype=int64)

In [30]:
data.weathersit.unique()

array([2, 1, 3], dtype=int64)

In [31]:
data["season"].value_counts()

3    188
2    184
1    181
4    178
Name: season, dtype: int64

In [32]:
data["yr"].value_counts()

1    366
0    365
Name: yr, dtype: int64

In [33]:
data["mnth"].value_counts()

12    62
10    62
8     62
7     62
5     62
3     62
1     62
11    60
9     60
6     60
4     60
2     57
Name: mnth, dtype: int64

In [35]:
data["holiday"].value_counts()

0    710
1     21
Name: holiday, dtype: int64

In [36]:
data["weekday"].value_counts()

6    105
1    105
0    105
5    104
4    104
3    104
2    104
Name: weekday, dtype: int64

In [37]:
data["workingday"].value_counts()

1    500
0    231
Name: workingday, dtype: int64

In [38]:
data["weathersit"].value_counts()

1    463
2    247
3     21
Name: weathersit, dtype: int64

In [41]:
corr=data.corr()
corr.nlargest(15,['cnt'])['cnt']

cnt           1.000000
registered    0.945517
casual        0.672804
atemp         0.631066
temp          0.627494
yr            0.566710
season        0.406100
mnth          0.279977
weekday       0.067443
workingday    0.061156
holiday      -0.068348
hum          -0.100659
windspeed    -0.234545
weathersit   -0.297391
Name: cnt, dtype: float64

In [45]:
data.head()

dteday  season  yr  mnth  holiday  weekday  workingday  weathersit  \
0  2011-01-01       1   0     1        0        6           0           2   
1  2011-01-02       1   0     1        0        0           0           2   
2  2011-01-03       1   0     1        0        1           1           1   
3  2011-01-04       1   0     1        0        2           1           1   
4  2011-01-05       1   0     1        0        3           1           1   

       temp     atemp       hum  windspeed  casual  registered   cnt  
0  0.344167  0.363625  0.805833   0.160446     331         654   985  
1  0.363478  0.353739  0.696087   0.248539     131         670   801  
2  0.196364  0.189405  0.437273   0.248309     120        1229  1349  
3  0.200000  0.212122  0.590435   0.160296     108        1454  1562  
4  0.226957  0.229270  0.436957   0.186900      82        1518  1600

In [48]:
data = data.drop(["dteday"],1)

In [49]:
data.head()

season  yr  mnth  holiday  weekday  workingday  weathersit      temp  \
0       1   0     1        0        6           0           2  0.344167   
1       1   0     1        0        0           0           2  0.363478   
2       1   0     1        0        1           1           1  0.196364   
3       1   0     1        0        2           1           1  0.200000   
4       1   0     1        0        3           1           1  0.226957   

      atemp       hum  windspeed  casual  registered   cnt  
0  0.363625  0.805833   0.160446     331         654   985  
1  0.353739  0.696087   0.248539     131         670   801  
2  0.189405  0.437273   0.248309     120        1229  1349  
3  0.212122  0.590435   0.160296     108        1454  1562  
4  0.229270  0.436957   0.186900      82        1518  1600

In [50]:
data.shape

(731, 14)

In [51]:
X = data.drop(["cnt"],1)

In [52]:
X.head()

season  yr  mnth  holiday  weekday  workingday  weathersit      temp  \
0       1   0     1        0        6           0           2  0.344167   
1       1   0     1        0        0           0           2  0.363478   
2       1   0     1        0        1           1           1  0.196364   
3       1   0     1        0        2           1           1  0.200000   
4       1   0     1        0        3           1           1  0.226957   

      atemp       hum  windspeed  casual  registered  
0  0.363625  0.805833   0.160446     331         654  
1  0.353739  0.696087   0.248539     131         670  
2  0.189405  0.437273   0.248309     120        1229  
3  0.212122  0.590435   0.160296     108        1454  
4  0.229270  0.436957   0.186900      82        1518

In [57]:
Y = data["cnt"].values

In [60]:
Y[0:5]

array([ 985,  801, 1349, 1562, 1600], dtype=int64)

In [62]:
from sklearn.model_selection import train_test_split

In [64]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [65]:
from sklearn.linear_model import LinearRegression

In [66]:
model=LinearRegression(normalize=True)
model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [67]:
model.coef_

array([-3.23049892e-13,  8.04712060e-13,  9.55595765e-14, -9.10288695e-13,
        1.45844194e-13,  4.88821853e-13,  1.74470202e-13,  8.39589762e-12,
       -3.33222225e-12, -4.56195266e-12, -3.90701389e-12,  1.00000000e+00,
        1.00000000e+00])

In [69]:
model.intercept_

-3.637978807091713e-12

In [71]:
model.rank_

13

In [72]:
model.singular_

array([1.83342223, 1.4363113 , 1.26711287, 1.14462722, 1.07496031,
       1.00986974, 0.94871907, 0.9118398 , 0.53481025, 0.45385494,
       0.39912467, 0.30214168, 0.10165433])

In [73]:
Y_pred=model.predict(X_test)
Y_pred

array([3830., 2114., 3915., 4322., 6591., 5204., 5323., 3351., 3068.,
       4972., 3351., 1977.,  822., 2485., 7736., 2368., 5515., 6572.,
       4511., 4359., 1851., 7335., 4758., 2689., 4966., 4118., 6824.,
       4375., 3389., 2475.,  754., 3523., 1683., 1749., 6241., 4570.,
       1416., 3368., 6591., 4023., 4553., 7424., 4840., 5728., 5202.,
       4717., 7338., 4035., 2277., 4866., 2034., 7693., 3403., 1812.,
       4304., 2947., 1969., 7006., 4656., 1927., 2376., 2134., 5084.,
       2121., 4154., 8294., 4592., 5319., 1685., 3204., 7261., 6825.,
       5035., 1562., 7444., 7415., 7765., 4507., 1872., 3310., 4826.,
       3376., 7570., 2402., 5267., 3659., 3126., 4150., 6864., 3574.,
       1005., 5058., 5138., 5342., 3005., 1746., 1000., 6891., 4665.,
       1341., 3577.,  985., 4367., 5047., 6192., 2192., 2594., 2169.,
       2133., 2302., 4058., 3644., 2425., 3740., 4788., 4509., 7458.,
       5538., 4066., 7273., 2496., 3761., 6597., 1693., 2918., 3322.,
       1421., 3333.,

In [77]:
compare = pd.DataFrame({"Actual" : Y_test, "Predcited" : Y_pred})

In [78]:
compare.head(10)

Actual  Predcited
0    3830     3830.0
1    2114     2114.0
2    3915     3915.0
3    4322     4322.0
4    6591     6591.0
5    5204     5204.0
6    5323     5323.0
7    3351     3351.0
8    3068     3068.0
9    4972     4972.0

In [79]:
data.head()

season  yr  mnth  holiday  weekday  workingday  weathersit      temp  \
0       1   0     1        0        6           0           2  0.344167   
1       1   0     1        0        0           0           2  0.363478   
2       1   0     1        0        1           1           1  0.196364   
3       1   0     1        0        2           1           1  0.200000   
4       1   0     1        0        3           1           1  0.226957   

      atemp       hum  windspeed  casual  registered   cnt  
0  0.363625  0.805833   0.160446     331         654   985  
1  0.353739  0.696087   0.248539     131         670   801  
2  0.189405  0.437273   0.248309     120        1229  1349  
3  0.212122  0.590435   0.160296     108        1454  1562  
4  0.229270  0.436957   0.186900      82        1518  1600

In [80]:
sample = data.iloc[500:505, :-1]

In [92]:
cntvalue = data.iloc[500:505,:14]

In [93]:
cntvalue

season  yr  mnth  holiday  weekday  workingday  weathersit      temp  \
500       2   1     5        0        2           1           2  0.611667   
501       2   1     5        0        3           1           1  0.636667   
502       2   1     5        0        4           1           1  0.593333   
503       2   1     5        0        5           1           1  0.564167   
504       2   1     5        0        6           0           1  0.600000   

        atemp       hum  windspeed  casual  registered   cnt  
500  0.576404  0.794583   0.147392     625        4490  5115  
501  0.595975  0.697917   0.122512     991        6433  7424  
502  0.572613  0.520000   0.229475    1242        6142  7384  
503  0.551121  0.523333   0.136817    1521        6118  7639  
504  0.566908  0.456250   0.083975    3410        4884  8294

In [81]:
sample

season  yr  mnth  holiday  weekday  workingday  weathersit      temp  \
500       2   1     5        0        2           1           2  0.611667   
501       2   1     5        0        3           1           1  0.636667   
502       2   1     5        0        4           1           1  0.593333   
503       2   1     5        0        5           1           1  0.564167   
504       2   1     5        0        6           0           1  0.600000   

        atemp       hum  windspeed  casual  registered  
500  0.576404  0.794583   0.147392     625        4490  
501  0.595975  0.697917   0.122512     991        6433  
502  0.572613  0.520000   0.229475    1242        6142  
503  0.551121  0.523333   0.136817    1521        6118  
504  0.566908  0.456250   0.083975    3410        4884

In [82]:
model.predict(sample)

array([5115., 7424., 7384., 7639., 8294.])

In [94]:
from sklearn.metrics import r2_score

In [95]:
r2_score(Y_test,Y_pred)

1.0

In [96]:
model.score(X_train,Y_train)

1.0

In [97]:
model.score(X_test,Y_test)

1.0